 for i in range(3):   
    f = open('param_test{}.ini'.format(k),'w')

    f.write('# input-output files and parameters\n')
    f.write('data_filename= test/shell{}.dat\n'.format(i))
    f.write('random_filename= test/random{}.dat\n'.format(i))
    f.write('#The next 2 files are only needed if you want to\n')
    f.write('#cross-correlate two datasets\n')
    f.write('data_filename_2= \n')
    f.write('random_filename_2= \n')
    f.write('input_format= 0\n')
    f.write('output_filename= test/multiple_task_{}.dat\n'.format(i))
    f.write('\n')
    f.write('# estimation parameters\n')
    f.write('corr_type= 3D_ps\n')
    f.write('\n')
    f.write('# cosmological parameters\n')
    f.write('omega_M= 0.31\n')
    f.write('omega_L= 0.69\n')
    f.write('w= -1\n')
    f.write('\n')
    f.write('# binning\n')
    f.write('log_bin= 0\n')
    f.write('dim1_max= 50.\n')
    f.write('dim1_min_logbin= 0.01\n')
    f.write('dim1_nbin= 50\n')
    f.write('dim2_max= 80.\n')
    f.write('dim2_nbin= 80\n')
    f.write('dim3_min= 0.4\n')
    f.write('dim3_max= 0.7\n')
    f.write('dim3_nbin= 1\n')
    f.write('\n')
    f.write('# pixels for radial correlation\n')
    f.write('radial_aperture= 1.\n')
    f.write('\n')
    f.write('# pm parameters\n')
    f.write('use_pm= 0\n')
    f.write('n_pix_sph= 2048\n')
    f.close()
